pipeline{
    agent any  //创建节点
    stages {  //阶段
        stage('') { //子阶段
            steps { //步骤1 buile ：构建编译打包
                bat ''
    // One or more steps need to be included within the steps block.
  }
}
}
}